name: CI

on: [pull_request]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Executes tests
      run: |
        swift test
